spring.application.name=medicure
server.port=8081

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:medicure
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
